name: Deploy to Bing Server

on:
  push:
    branches:
      - bing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: bing

    steps: 
      - name: 拉代码
        uses: actions/checkout@master

      - name: 配置一个nodejs环境
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_DOTCOM_TOKEN }}
          node-version: 16
        script:
          cd service
          npm install
          npm run build

      - name: 把构建好的代码发到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: service/dist
          remote: /root/cbh/vue-admin-projects/nest-service
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          concurrency: 20

